### ISSUE TITLE
Duplicate word detection

### ISSUE THREAD

**Issue by psychemedia** [facelessuser/pyspelling#142]
To make this tool a little bit more general, I wonder how easy it would be to also add in a report based on repeated word detection?

eg trivially, `egrep -o  "\b(\w+)\s+\1\b" $FILEPATH_REGEX` will return repeated word matches (ish!).

**Comment by facelessuser** [comment]
I do appreciate the suggestion, but while it may or may not be trivial to add such behavior, it is really beyond the scope of the project.

I don't think at this time I'm open to rebranding and extending its functionality beyond spelling. This project's whole purpose is simply to help catch misspelled words. I had a need for it in my projects which is why I spent the time creating it.

This project doesn't perform grammar checks, or other word related tasks. If I ever did go down this path, it would probably be in a new project, named in such a way as to reflect such behavior, but I do not have such plans at this time.
