### ISSUE TITLE
Interested in Restructured Text Filter

### ISSUE THREAD

**Issue by timgates42** [facelessuser/pyspelling#88]
I'm thinking of implementing a restructured text filter similar to the markdown filter that just uses docutils to convert from restructured text into html which can then use the normal html filter pipeline. Just raising as an issue first for discussion in case its already been tried and there were significant hidden issues or if it is just a case of no existing requirement. Thanks for the great library and also the feedback on my previous contributions.

**Comment by facelessuser** [comment]
The current plugins were written as I had an immediate use or thought I may like to use them in the future. Outside of that, I didn't really think to much about things like restructured text; I don't use restructured text very often.

I think a restructured plugin would be very cool though, and I'd love to see one get developed. I hesitate to say that I would want it to live directly in pyspelling though, not because it wouldn't be useful, but that it would be another plugin I'd have to maintain. I think such things are always better when maintained by someone that actively uses it. For that reason, my preference would be for it to live as a 3rd party plugin..

With all of that said I'd be more than happy to offer any advise  or help if you need any.

**Comment by timgates42** [comment]
Thanks @facelessuser I hadn't even considered not being part of pyspelling - that is a totally understandable position and I'm certainly happy with the suggestion of starting a 3rd party plugin. If you don't mind before I close this issue I will add a link to the new plugin once I've set it up.

**Comment by timgates42** [comment]
I've setup the starting point for the repository in case others come later and find this issue. Its not ready yet but I'll add the links and close the item:

https://github.com/resplendent-dev/resplendent

**Comment by facelessuser** [comment]
Sounds good. Feel free to ask any questions you might have during development of your plugin.
